version: '3'
services:

  pg-db:
    image: postgres:14.3
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PRISMA_POSTGRES_DBNAME: ${PRISMA_POSTGRES_DBNAME}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - '5432:5433'
    volumes: 
      - ./db:/docker-entrypoint-initdb.d/
      - ./db/postgres:/var/lib/postgresql/data
  
  prisma-postgres:
    build:
      dockerfile: apps/prisma-postgres/Dockerfile
      context: ./
    container_name: prisma-postgres
    image: prisma-postgres
    ports:
      - "3050:3050"
    restart: always
    depends_on:
      - "pg-db"
    environment:
      NODE_ENV: ${NODE_ENV}
      PG_HOST: ${PG_HOST}
      SERVER_PORT: 3050
      PG_PORT: 5432
      PG_DATABASE: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PRISMA_POSTGRES_DBNAME: ${PRISMA_POSTGRES_DBNAME}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}

    # volumes:
    #   - .:/apps
    #   - ./node_modules
